title: olivermak.es
author:
  name: Oliver Pattison
  email: oliverpattison@gmail.com
description: 'I am a designer focused on the future of the web.'

url: http://olivermak.es
image-url: http://static.olivermak.es/images
scripts-url: http://static.olivermak.es/scripts

photo-sizes: '(min-width: 140em) 1440px, (min-width: 115em) 1260px, (min-width: 95em) 1080px, (min-width: 60em) 900px, (min-width: 45em) 720px, 100vw'
photo-sizes_half: '(min-width: 140em) 691px, (min-width: 115) 605px, (min-width: 95em) 518px, (min-width: 60em) 432px, (min-width: 45em) 720px, 100vw'
srcset:
  - 480
  - 640
  - 720
  - 900
  - 1080
  - 1260
  - 1440
srcset_half:
  - 480
  - 640
  - 720
  - 900
  - 1080

markdown: kramdown
permalink: /:year/:month/:title/

exclude: [s3_website.yml, Rakefile, _images]