title: olivermak.es
author:
  name: Oliver Pattison
  email: oliverpattison@gmail.com
description: 'I am a designer focused on the future of the web.'

url: http://olivermak.es
image-url: http://static.olivermak.es/images
script-url: http://static.olivermak.es/scripts

photo-sizes: '(min-width: 140em) 1440px, (min-width: 115em) 1260px, (min-width: 95em) 1080px, (min-width: 60em) 900px, (min-width: 45em) 720px, 100vw'
photo-sizes_half: '(min-width: 140em) 691px, (min-width: 115) 605px, (min-width: 95em) 518px, (min-width: 60em) 432px, (min-width: 45em) 720px, 100vw'
srcset:
  - 480
  - 640
  - 720
  - 900
  - 1080
  - 1260
  - 1440
srcset_half:
  - 480
  - 640
  - 720
  - 900
  - 1080

markdown: kramdown
permalink: /:year/:month/:title/

exclude: [s3_website.yml, Rakefile, _images]

# shades

shade:
  - name: black
    hsl: 'hsla(204, 10%, 10%, 1)'
    hex: '#1c1f22'
  - name: gray1
    hsl: 'hsla(204, 10%, 18%, 1)'
    hex: '#292f32'
  - name: gray2
    hsl: 'hsla(204, 10%, 24%, 1)'
    hex: '#373e43'
  - name: gray3
    hsl: 'hsla(204, 10%, 32%, 1)'
    hex: '#49535a'
  - name: gray4
    hsl: 'hsla(204, 10%, 40%, 1)'
    hex: '#5c6870'
  - name: gray6
    hsl: 'hsla(204, 10%, 56%, 1)'
    hex: '#84919a'
  - name: gray8
    hsl: 'hsla(204, 10%, 80%, 1)'
    hex: '#c7cdd1'
  - name: gray9
    hsl: 'hsla(204, 10%, 88%, 1)'
    hex: '#dde1e3'
  - name: offwhite
    hsl: 'hsla(204, 10%, 96%, 1)'
    hex: '#f4f5f6'
  - name: white
    hsl: 'hsla(204, 10%, 98%, 1)'
    hex: '#f9fafa'
  - name: transparent
    hsl: 'hsla(0, 0%, 100%, .01)'

#colors

color:
  - name: blue
    hsl: 'hsla(204, 50%, 45%, 1)'
    hex: '#397eac'
  - name: boldblue
    hsl: 'hsla(204, 80%, 40%, 1)'
    hex: '#1476b8'
  - name: grayblue
    hsl: 'hsla(204, 30%, 80%, 1)'
    hex: '#bdcfdb'
  - name: graybluetransparent
    hsl: 'hsla(204, 30%, 80%, .5)'
  - name: red
    hsl: 'hsla(4, 60%, 50%, 1)'
    hex: '#cc3d33'
  - name: boldred
    hsl: 'hsla(4, 80%, 40%, 1)'
    hex: '#bd1b0f'
  - name: pink
    hsl: 'hsla(4, 30%, 80%, 1)'
    hex: '#dbbfbd'
  - name: pinktransparent
    hsl: 'hsla(4, 30%, 80%, .5)'
  - name: orange
    hsl: 'hsla(22, 50%, 44%, 1)'
    hex: '#a86138'
  - name: gold
    hsl: 'hsla(44, 50%, 44%, 1)'
    hex: '#a88a38'
  - name: lightgold
    hsl: 'hsla(44, 30%, 88%, 1)'
    hex: '#eae5d7'
  - name: green
    hsl: 'hsla(144, 50%, 35%, 1)'
    hex: '#2d8650'
  - name: bluegreen
    hsl: 'hsla(184, 32%, 38%, 1)'
    hex: '#427c80'
  - name: violet
    hsl: 'hsla(225, 35%, 52%, 1)'
    hex: '#5a6faf'