title: olivermak.es
author:
  name: Oliver Pattison
  email: oliverpattison@gmail.com
description: 'I am a designer focused on the future of the web.'

url: http://olivermak.es
image-url: http://static.olivermak.es/images
scripts-url: http://static.olivermak.es/scripts

photo-sizes: '(min-width: 120em) 75vw, (min-width: 100em) 78.75vw, (min-width: 80em) 84.375vw, (min-width: 60em) 93.75vw, 100vw'
photo-sizes_half: '(min-width: 120em) 36vw, (min-width: 100em) 37.68vw, (min-width: 80em) 40.32vw, (min-width: 60em) 45vw, 100vw'
srcset:
  - 480
  - 640
  - 720
  - 900
  - 1080
  - 1260
  - 1440

markdown: kramdown
permalink: /:year/:month/:title/

exclude: [s3_website.yml, Rakefile, _images]