title: Oliver Pattison
author:
  name: Oliver Pattison
  email: oliverpattison@gmail.com
description: 'I’m a designer focused on the future of the web.'

url: http://olivermak.es
image_url: http://static.olivermak.es/images
scripts_url: http://static.olivermak.es/scripts

markdown: kramdown
permalink: /:year/:month/:title/

exclude: [s3_website.yml, Rakefile, _images]