# Site configuration

## Gems configuration
gems:
  - jekyll-archives
  - sass
# - octopress-autoprefixer
  - imgix

## Imgix configuration
imgix:
  source: dev-olivermakes.imgix.net

## Sass configuration
sass:
  sass_dir: _sass
  style: expanded
